spring:
  application:
    name: recommendationengine
  cloud:
    stream:
      bindings:
        output:
          destination: userProfileChangeTopic
          content-type: application/json
        kafka:
          binder:
            zkNodes: localhost
            binders: localhost
logging:
  level: info
