spring:
  application:
    name: licensingservice
  cloud:
    stream:
      bindings:
        input:
          destination: userProfileChangeTopic
          content-type: application/json
          group: profileServersGroup
